"""initial schema

Revision ID: 83e7a02e027a
Revises: 
Create Date: 2026-06-03 11:08:03.090549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '83e7a02e027a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_hwid_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'staff', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('trial_7', 'monthly_30', 'unlimited', 'custom', name='plan_type'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='license_status'), nullable=False),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_contact', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('max_hwid_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_licenses_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_product_id'), ['product_id'], unique=False)

    op.create_table('activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('client_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'hwid', name='uq_activation_license_hwid')
    )
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activations_hwid'), ['hwid'], unique=False)
        batch_op.create_index(batch_op.f('ix_activations_license_id'), ['license_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('issue', 'verify_success', 'verify_fail', 'revoke', 'extend', 'hwid_register', 'hwid_conflict', 'hwid_release', 'login', name='audit_event_type'), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hwid', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_license_id'), ['license_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_license_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activations_license_id'))
        batch_op.drop_index(batch_op.f('ix_activations_hwid'))

    op.drop_table('activations')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_product_id'))
        batch_op.drop_index(batch_op.f('ix_licenses_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_licenses_key_hash'))

    op.drop_table('licenses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_code'))

    op.drop_table('products')
    # ### end Alembic commands ###
